import { Montserrat } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Theme/ThemeLayout";

const montserrat = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout className={` ${montserrat.variable} antialiased`}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
